language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "thejustinh-github"
    token:
      secure: "014fef19af96795933252cd5a5c62f92e3635251"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
